apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: sample-weblogic-comp
  namespace: sample-weblogic
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoWebLogicWorkload
    spec:
      template:
        metadata:
          name: sample-weblogic
          namespace: sample-weblogic
          labels:
            weblogic.resourceVersion: domain-v8
            weblogic.domainUID: sample-domain1
        spec:
          domainUID: sample-domain1
          domainHome: /u01/oracle/user_projects/domains/sample-domain1
          image: iad.ocir.io/weblogick8s/weblogic-operator-tutorial-store-14.1.1-psu:1.0
          #imagePullSecrets:
          #  - name: sample-weblogic-image-credentials
          domainHomeSourceType: "FromModel"
          includeServerOutInPodLog: true
          replicas: 1
          webLogicCredentialsSecret:
            name: sample-domain1-weblogic-credentials
          clusters:
            - clusterName: cluster-1
          configuration:
            introspectorJobActiveDeadlineSeconds: 600
            model:
              runtimeEncryptionSecret: runtime-encryption-secret
          monitoringExporter:
            imagePullPolicy: IfNotPresent
            configuration:
              metricsNameSnakeCase: true
              domainQualifier: true
              queries:
                - key: name
                  keyName: location
                  prefix: wls_server_
                  applicationRuntimes:
                    key: name
                    keyName: app
                    componentRuntimes:
                      prefix: wls_webapp_config_
                      type: WebAppComponentRuntime
                      key: name
                      values: [ deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount ]
                      servlets:
                        prefix: wls_servlet_
                        key: servletName
                - JVMRuntime:
                    prefix: wls_jvm_
                    key: name
          serverPod:
            env:
              - name: JAVA_OPTIONS
                value: "-Dweblogic.StdoutDebugEnabled=false"
              - name: USER_MEM_ARGS
                value: "-Djava.security.egd=file:/dev/./urandom"
              - name: WL_HOME
                value: /u01/oracle/wlserver
              - name: MW_HOME
                value: /u01/oracle
